#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705 - Deiteq
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  vars:
    service_vars:
      - {name: permissions.service}

  - name: Checking Existing Service Name
    stat:
      path: "/etc/systemd/system/{{ item.name }}"
    with_items: "{{ service_vars }}"
    register: check_service_name

  - name: Stop If Service Is Running
    systemd: state=stopped name={{ item.item.name }} daemon_reload=yes enabled=no
    with_items: "{{ check_service_name.results }}"
    when: item.stat.exists

  - name: Remove Services
    file:
      path: "/etc/systemd/system/{{ item.item.name }}"
      state: absent
    with_items: "{{ check_service_name.results }}"
    when: item.stat.exists

  - name: "Install - Permissions Service"
    template:
      src: "/pg/stage/service/permissions.service"
      dest: "/etc/systemd/system/permisisons.service"
      force: yes
    ignore_errors: yes

  - name: "Reloading Permissions Service"
    systemd:
      daemon_reload: yes
      enabled: yes
      state: reloaded
      name: "permissions"
