#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
source /pg/pgblitz/menu/functions/functions.sh
source /pg/pgblitz/menu/functions/start.sh

sudocheck
missingpull
exitcheck
