#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
source /pg/stage/functions/install.sh

mkdir -p /pg/pgblitz/roles/log
mkdir -p /pg/var/logs
mkdir -p /pg/data/blitz

sudocheck
missingpull
# pg deploy contains pgdeploy at end
pginstall
