#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
source /pg/stage/functions/sudocheck.sh
source /pg/stage/functions/restorecheck.sh
source /pg/stage/functions/endingcheck.sh
source /pg/stage/version/file.sh

sudocheck
echo 1
restorecheck
echo 2
mainstart
echo 3
endingcheck
echo 4
