#!/bin/bash
#
# Title:      PGBlitz (Reference Title File)
# Author(s):  Admin9705
# URL:        https://pgblitz.com - http://github.pgblitz.com
# GNU:        General Public License v3.0
################################################################################
path27="/pg/stage/functions"

source "${path27}/core.sh"
source "${path27}/keyvars.sh"
source "${path27}/install.sh"
source "${path27}/pginstall.sh"

# Execute Key Variables from keyvars.sh
keyvars

# Make Critical Folders
var59="/pg /pg/logs /pg/var /pg/data /pg/stage /pg/logs /pg/tmp"
mkdir -p "${var59}"
chmod 775 "${var59}"
chown 1000:1000 "${var59}"

# Ensures the user has proper permissions
#sudocheck

if [[ ! -e "/bin/pgblitz" ]]; then
  cp /opt/plexguide/menu/alias/templates/pgblitz /bin/ &>/dev/null &
  chown 1000:1000 /bin/pgblitz
  chmod 0755 /bin/pgblitz
fi

# if new install or update is conducted, runs through pginstall
if [ -e "/pg/var/new.install" ]; then pginstall;
elif [ -e "/pg/var/update.install" ]; then pginstall; fi
